Add RESISC45 Dataset
jakartaresearch/earth-vision pull request #47
Opened 2021-05-20 13:55 UTC by andreaschandra

To do

- [ ] dataset class
- [ ] downloader

2021-05-22 04:28 UTC, andreaschandra commented
@rubentea16 review

2021-05-22 09:41 UTC, rubentea16 requested changes
[IMPROVEMENT]

CLASS_DEC  = {y:x for x,y in CLASS_ENC}

@andreaschandra @dwiuzila

2021-05-22 10:27 UTC, rubentea16 requested changes

2021-05-22 10:27 UTC, rubentea16 commented on earthvision/datasets/utils.py
> +import torch
Ini `import torch` disini buat apa?

2021-05-22 10:27 UTC, rubentea16 commented on earthvision/datasets/resisc45.py
> +    def __init__(self, root, transform=None, target_transform=None):
Buat dataset ini ga ada "data_mode" ? train/val/test data nya

2021-05-22 10:54 UTC, andreaschandra commented on earthvision/datasets/resisc45.py
> +    def __init__(self, root, transform=None, target_transform=None):
ga ada. gw lihat punya torchvision juga ada yang ga ada split nya. mau dibikin sendiri. nanti aja keknya

2021-05-22 10:54 UTC, andreaschandra commented
> [IMPROVEMENT]
> 
> CLASS_DEC = {y:x for x,y in CLASS_ENC}
> 
> @andreaschandra @dwiuzila

@dwiuzila di config nya nih

2021-05-22 10:59 UTC, andreaschandra commented on earthvision/datasets/utils.py
> +import torch
@dwiuzila

2021-05-22 10:59 UTC, andreaschandra commented on earthvision/datasets/utils.py
> +import torch
eh udah nih

2021-05-22 10:59 UTC, andreaschandra commented on earthvision/datasets/__init__.py
>  from .aerial_cactus import AerialCactus
doen

2021-05-23 00:05 UTC, dwiuzila commented
> > [IMPROVEMENT]
> > CLASS_DEC = {y:x for x,y in CLASS_ENC}
> > @andreaschandra @dwiuzila
> 
> @dwiuzila di config nya nih

ini udah ya

2021-05-23 13:14 UTC, rubentea16 approved these changes

2021-05-23 13:26 UTC, merged