Sentinel 2 Cloud Dataset
jakartaresearch/earth-vision pull request #68
Opened 2021-07-13 12:15 UTC by kokoedwin

2021-07-14 05:35 UTC, andreaschandra commented
review @rubentea16

2021-07-15 14:20 UTC, rubentea16 requested changes

2021-07-15 14:20 UTC, rubentea16 commented on earthvision/datasets/sentinel2cloud.py
> +            yield self.__getitem__(index)
`__iter__` => unnecessary

2021-07-15 14:24 UTC, rubentea16 commented
@kokoedwin @FendiSuryadinata570

2021-07-22 12:35 UTC, rubentea16 commented on earthvision/datasets/sentinel2cloud.py
> +        if os.path.exists(self.root):
just use `if not os.path.exists(self.root): os.makedirs(self.root)`

2021-07-22 14:12 UTC, rubentea16 approved these changes

2021-07-22 14:15 UTC, rubentea16 commented
silahkan di merge @kokoedwin @FendiSuryadinata570

2021-07-22 14:39 UTC, merged