Spacenet7
jakartaresearch/earth-vision pull request #71
Opened 2021-07-22 13:41 UTC by rubentea16

@ryzary

2021-07-24 16:24 UTC, andreaschandra requested changes

2021-07-24 18:17 UTC, rubentea16 commented on earthvision/__init__.py
> +import geopandas
sblmnya crash klo kaga import wkwk, tpi skrg udh bisa

2021-07-25 08:05 UTC, andreaschandra commented on environment.yml
> +name: earth-vision
ini khusus installation pake conda ya?

2021-07-25 08:05 UTC, andreaschandra commented on earthvision/datasets/utils.py
> +def s3_downloader(s3_client, local_file_name, s3_bucket, s3_object_key):
@rubentea16  @ryzary

2021-07-25 08:06 UTC, andreaschandra requested changes

2021-07-25 08:06 UTC, andreaschandra commented on earthvision/datasets/utils.py
> +def downloader(resource, root):
sekalian docstring variable type & description

2021-07-25 09:45 UTC, rubentea16 commented on environment.yml
> +name: earth-vision
package `gdal` kalo install lewat pip error, yg bisa dan aman install lewat conda. gw propose u/ default installation nya pake conda aja drpada pip

2021-07-26 17:01 UTC, rubentea16 commented
@andreaschandra

2021-07-27 13:16 UTC, andreaschandra approved these changes
@rubentea16 @ryzary go merge

2021-07-27 13:17 UTC, merged