Enabled So2Sat Data Class
jakartaresearch/earth-vision pull request #74
Opened 2021-08-02 12:16 UTC by juannat7

2021-08-14 11:15 UTC, andreaschandra requested changes
require some changes

2021-08-14 11:15 UTC, andreaschandra commented on earthvision/datasets/so2sat.py
> +    def __iter__(self):
kita udah ga pake __iter__ lagi, karena bisa langsung tanpa ini

2021-08-14 11:15 UTC, andreaschandra commented on earthvision/datasets/so2sat.py
> +
tambahin `from torch.utils.data import Dataset`

2021-08-14 11:15 UTC, andreaschandra commented on earthvision/datasets/so2sat.py
> +class So2Sat():
disini jadi `So2Sat(Dataset)`

2021-08-14 12:19 UTC, andreaschandra commented
@juannat7 @dwiuzila

2021-08-29 01:03 UTC, andreaschandra commented
@dwiuzila oh fix conflicting files di `datasets/__ini__.py`

2021-08-29 01:08 UTC, andreaschandra approved these changes

2021-08-29 11:32 UTC, dwiuzila approved these changes

2021-08-29 12:20 UTC, merged